-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               10.4.13-MariaDB - mariadb.org binary distribution
-- Server OS:                    Win64
-- HeidiSQL Version:             11.0.0.5919
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;


-- Dumping database structure for redemrp
CREATE DATABASE IF NOT EXISTS `redemrp` /*!40100 DEFAULT CHARACTER SET utf8mb4 */;
USE `redemrp`;

-- Dumping structure for table redemrp.keys
CREATE TABLE IF NOT EXISTS `keys` (
  `key` varchar(50) DEFAULT NULL,
  `holder` varchar(60) DEFAULT NULL,
  `roommate` varchar(60) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Dumping data for table redemrp.keys: ~200 rows (approximately)
/*!40000 ALTER TABLE `keys` DISABLE KEYS */;
INSERT IGNORE INTO `keys` (`key`, `holder`, `roommate`) VALUES
	('key_1_1', '', ''),
	('key_1_2', '', ''),
	('key_1_3', '', NULL),
	('key_2_1', '', NULL),
	('key_2_2', '', NULL),
	('key_2_3', '', NULL),
	('key_2_4', '', NULL),
	('key_2_5', '', NULL),
	('key_2_6', '', NULL),
	('key_2_7', '', NULL),
	('key_2_8', '', NULL),
	('key_2_9', '', NULL),
	('key_2_10', '', NULL),
	('key_2_11', '', NULL),
	('key_2_12', '', NULL),
	('key_2_13', '', NULL),
	('key_2_14', '', NULL),
	('key_2_15', '', NULL),
	('key_2_16', '', NULL),
	('key_2_17', '', NULL),
	('key_2_18', '', NULL),
	('key_2_19', '', NULL),
	('key_2_20', '', NULL),
	('key_2_21', '', NULL),
	('key_2_22', '', NULL),
	('key_2_23', '', NULL),
	('key_2_24', '', NULL),
	('key_2_25', '', NULL),
	('key_2_26', '', NULL),
	('key_2_27', '', NULL),
	('key_2_28', '', NULL),
	('key_2_29', '', NULL),
	('key_2_30', '', NULL),
	('key_2_31', '', NULL),
	('key_2_32', '', NULL),
	('key_2_33', '', NULL),
	('key_2_34', '', NULL),
	('key_2_35', '', NULL),
	('key_2_36', '', NULL),
	('key_2_37', '', NULL),
	('key_3_1', '', NULL),
	('key_3_2', '', NULL),
	('key_3_3', '', NULL),
	('key_3_4', '', NULL),
	('key_3_5', '', NULL),
	('key_3_6', '', NULL),
	('key_3_7', '', NULL),
	('key_3_8', '', NULL),
	('key_3_9', '', NULL),
	('key_3_10', '', NULL),
	('key_3_11', '', NULL),
	('key_3_12', '', NULL),
	('key_3_13', '', NULL),
	('key_3_14', '', NULL),
	('key_3_15', '', NULL),
	('key_3_16', '', NULL),
	('key_3_17', '', NULL),
	('key_3_18', '', NULL),
	('key_3_19', '', NULL),
	('key_3_20', '', NULL),
	('key_3_21', '', NULL),
	('key_3_22', '', NULL),
	('key_3_23', '', NULL),
	('key_3_24', '', NULL),
	('key_3_25', '', NULL),
	('key_3_26', '', NULL),
	('key_3_27', '', NULL),
	('key_3_28', '', NULL),
	('key_3_29', '', NULL),
	('key_3_30', '', NULL),
	('key_3_31', '', NULL),
	('key_3_32', '', NULL),
	('key_3_33', '', NULL),
	('key_3_34', '', NULL),
	('key_3_35', '', NULL),
	('key_3_36', '', NULL),
	('key_3_37', '', NULL),
	('key_3_38', '', NULL),
	('key_3_39', '', NULL),
	('key_3_40', '', NULL),
	('key_3_41', '', NULL),
	('key_3_42', '', NULL),
	('key_3_43', '', NULL),
	('key_3_44', '', NULL),
	('key_3_45', '', NULL),
	('key_3_46', '', NULL),
	('key_3_47', '', NULL),
	('key_3_48', '', NULL),
	('key_3_49', '', NULL),
	('key_3_50', '', NULL),
	('key_3_51', '', NULL),
	('key_3_52', '', NULL),
	('key_3_53', '', NULL),
	('key_3_54', '', NULL),
	('key_3_55', '', NULL),
	('key_3_56', '', NULL),
	('key_3_57', '', NULL),
	('key_3_58', '', NULL),
	('key_3_59', '', NULL),
	('key_3_60', '', NULL),
	('key_3_61', '', NULL),
	('key_3_62', '', NULL),
	('key_3_63', '', NULL),
	('key_3_64', '', NULL),
	('key_3_65', '', NULL),
	('key_3_66', '', NULL),
	('key_3_67', '', NULL),
	('key_3_68', '', NULL),
	('key_3_69', '', NULL),
	('key_3_70', '', NULL),
	('key_3_71', '', NULL),
	('key_3_72', '', NULL),
	('key_3_73', '', NULL),
	('key_3_74', '', NULL),
	('key_3_75', '', NULL),
	('key_3_76', '', NULL),
	('key_3_77', '', NULL),
	('key_3_78', '', NULL),
	('key_3_79', '', NULL),
	('key_3_80', '', NULL),
	('key_3_81', '', NULL),
	('key_3_82', '', NULL),
	('key_3_83', '', NULL),
	('key_3_84', '', NULL),
	('key_3_85', '', NULL),
	('key_3_86', '', NULL),
	('key_3_87', '', NULL),
	('key_3_88', '', NULL),
	('key_3_89', '', NULL),
	('key_3_90', '', NULL),
	('key_3_91', '', NULL),
	('key_4_1', '', NULL),
	('key_4_2', '', NULL),
	('key_4_3', '', NULL),
	('key_4_4', '', NULL),
	('key_4_5', '', NULL),
	('key_4_6', '', NULL),
	('key_4_7', '', NULL),
	('key_4_8', '', NULL),
	('key_4_9', '', NULL),
	('key_4_10', '', NULL),
	('key_5_1', '', NULL),
	('key_5_2', '', NULL),
	('key_5_3', '', NULL),
	('key_5_4', '', NULL),
	('key_5_5', '', NULL),
	('key_5_6', '', NULL),
	('key_5_7', '', NULL),
	('key_5_8', '', NULL),
	('key_5_9', '', NULL),
	('key_5_10', '', NULL),
	('key_5_11', '', NULL),
	('key_5_12', '', NULL),
	('key_5_13', '', NULL),
	('key_5_14', '', NULL),
	('key_5_15', '', NULL),
	('key_5_16', '', NULL),
	('key_5_17', '', NULL),
	('key_5_18', '', NULL),
	('key_5_19', '', NULL),
	('key_5_20', '', NULL),
	('key_5_21', '', NULL),
	('key_5_22', '', NULL),
	('key_5_23', '', NULL),
	('key_6_1', '', NULL),
	('key_6_2', '', NULL),
	('key_6_3', '', NULL),
	('key_6_4', '', NULL),
	('key_6_5', '', NULL),
	('key_6_6', '', NULL),
	('key_6_7', '', NULL),
	('key_6_8', '', NULL),
	('key_6_9', '', NULL),
	('key_6_10', '', NULL),
	('key_6_11', '', NULL),
	('key_6_12', '', NULL),
	('key_6_13', '', NULL),
	('key_6_14', '', NULL),
	('key_6_15', '', NULL),
	('key_6_16', '', NULL),
	('key_7_1', '', NULL),
	('key_7_2', '', NULL),
	('key_7_3', '', NULL),
	('key_7_4', '', NULL),
	('key_7_5', '', NULL),
	('key_7_6', '', NULL),
	('key_7_7', '', NULL),
	('key_7_8', '', NULL),
	('key_7_9', '', NULL);
/*!40000 ALTER TABLE `keys` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
